config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'logins#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :users
  get '/password', to: 'users#password'
    
  get '/register', to: 'users#new'
  
  resources :reports
  resources :receipts
  resources :subjects
  resources :purchasers
  resources :puroptions
  resources :uploads
  resources :vendors
  resources :departments
  resources :images 
  resources :receipts do
    resources :images
  end

end

app/models/purchaser.rb
class Purchaser < ActiveRecord::Base
	#belongs_to :receipts
	has_many :receipts
	validates :purchaser_name, presence: true, length: { minimum: 2, maximum: 30 }
	validates :worker_category, presence: true, length: { minimum: 2, maximum: 30 }	


end

app/controllers/purchasers_controller.rb
class PurchasersController < ApplicationController 
	before_action :require_user
	before_action :require_active_user
	before_action :require_admin_user, only: [:index, :edit, :update, :show]

	def index
		@purchasers = Purchaser.paginate(page: params[:page], per_page: 10)
	end
	
	def show
		@purchaser = Purchaser.find(params[:id])
		@receipts = @purchaser.receipts
	end

	def new
		@purchaser = Purchaser.new
	end
	def edit
		@purchaser = Purchaser.find(params[:id])
	end
	def update
		@purchaser = Purchaser.find(params[:id])
		if @purchaser.update(purchaser_params)
			flash[:success] = "The Purchaser has been updated succesfully"
			redirect_to purchasers_path
		else
			render 'edit'
		end
	end
	
	def create
		@purchaser = Purchaser.new(purchaser_params)

		if @purchaser.save
			flash[:success] = "Purchaser created succesfully."
			redirect_to purchasers_path
		else
			render 'new'
		end

	end

	private
	def purchaser_params
		params.require(:purchaser).permit(:purchaser_name, :worker_category)
	end

end

app/views/purchasers/_form.html.erb
<%= render 'shared/errors', obj: @purchaser %>
<div class="row">
	<div class="well col-xs- col-lg-8 col-lg-offset-2 col-xs-offset-2 center">
		<%= form_for @purchaser do |f| %>
		<h5 class="bold left line_Up">Purchaser Name:</h5>
		<%= f.text_field :purchaser_name %>
		<h5 class="bold left line_Up">Job Title:</h5>
		<%= f.text_field :worker_category %>
	
		<%= f.submit(@purchaser.new_record? ? "Create Purchaser" : "Edit Purchaser", class: "btn btn-success") %>
		<% end %>
	</div>
</div>

app/views/purchasers/edit.html.erb
<%= render 'shared/page_title', title: "Edit Purchaser" %>
<%= render 'form' %>

app/views/purchasers/index.html.erb
<%= render 'shared/page_title', title: "All Purchasers" %>
<p><%= link_to new_purchaser_path do %>
    <i class="btn btn-lg btn-success floatright" >Add Purchaser</i>
    <% end %>
</p>

<div class="table-container col-lg-6 col-lg-offset-3 col-xs-12">
	<table class="data-table">
		<thead>
			<tr>
				<th>Purchaser Name</th>
				<th>Worker Category</th>
				<th>Edit</th>
			</tr>
		</thead>
		<% @purchasers.each do |purchaser| %>

		<tbody>
			<tr>
				<td><%= purchaser.purchaser_name %></td>
                <td><%= purchaser.worker_category %></td>
                <td><%= link_to purchaser_path(purchaser) do %>
                        <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
                    <% end %>     
                    <%= link_to edit_purchaser_path(purchaser) do %>
                        <i class="glyphicon glyphicon-cog" style="color:grey"></i> </td>
                    <% end %></td>
			</tr>		
		</tbody>
		<% end %>
	</table>
	    

      
      <div class="row">
                <div class= "center">
                <%= will_paginate %>
                </div>
       </div>
</div>

app/views/purchasers/new.html.erb
<%= render 'shared/page_title', title: "Create Purchaser" %>
<%= render 'form' %>

app/views/purchasers/show.html.erb
<h1 class="title_size"> Purchaser: <%= @purchaser.purchaser_name  %></h1>
<hr>
<h5 class="center">Purchaser Work Description: <%= @purchaser.worker_category  %> </h5>       
<h5 class="center">Purchaser Created <%= time_ago_in_words(@purchaser.created_at) %> ago</h5>
<h5 class="center">Purchaser Last Updated <%= time_ago_in_words(@purchaser.updated_at) %> ago</h5>      



<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
				<th>Date</th>
				<th>Subject</th>
				<th>Vendor</th>
				<th>Department</th>
				<th>Purchaser</th>
				<th>Purchase Option</th>
				<th>Tax Paid</th>
				<th>Total Amount</th>
				<th>Options</th>
			</tr>
		</thead>
		
        <% @receipts.each do |receipt| %>
        <tbody>
			<tr>
				<td><%= receipt.date.try(:strftime, "%m/%d/%Y") %></td>
				<td><%= receipt.subject.subject_name %></td>
				<td><%= receipt.vendor.vendor_name %></td>
				<td><%= receipt.department.department_name %></td>
				<td><%= receipt.purchaser.purchaser_name %></td>
			    	<td><%= receipt.puroption.puroption_name %></td>
				<td>$<%= receipt.tax_amount %></td>
				<td>$<%= receipt.purchase_amount %></td>
				
                <td><%= link_to receipt_path(receipt) do %>
                        <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
                    <% end %>            
              		  <%= link_to edit_receipt_path(receipt) do %>
                        <i class="glyphicon glyphicon-cog" style="color:grey"></i>
                    <% end %></td> </td>
			</tr>		
		</tbody>
        <% end %>
        <tr> 
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td bgcolor="#FFFF00">Total</td>
        <td bgcolor="#FFFF00"> $<%= @purchaser.receipts.sum(:tax_amount) %> </td>
        <td bgcolor="#FFFF00"> $<%= @purchaser.receipts.sum(:purchase_amount) %> </td>
        <td></td>
        </tr>
        
        </table>

</div>