config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'logins#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :users
  get '/password', to: 'users#password'
    
  get '/register', to: 'users#new'
  
  resources :reports
  resources :receipts
  resources :subjects
  resources :purchasers
  resources :puroptions
  resources :uploads
  resources :vendors
  resources :departments
  resources :images 
  resources :receipts do
    resources :images
  end

end

app/models/puroption.rb
class Puroption < ActiveRecord::Base
	#belongs_to :receipts
	has_many :receipts
	validates :puroption_name, presence: true, length: { minimum: 2, maximum: 30 }
	validates :description, presence: true, length: { minimum: 2, maximum: 200 }


	
end

app/controllers/puroptions_controller.rb
class PuroptionsController < ApplicationController 
	before_action :require_user
	before_action :require_active_user
	before_action :require_admin_user, only: [:index, :edit, :update, :show]

	def index
		@puroptions = Puroption.paginate(page: params[:page], per_page: 10)
	end
	
	def show
		@puroption = Puroption.find(params[:id])
		@receipts = @puroption.receipts
	end

	def new
		@puroption = Puroption.new
	end
	def edit
		@puroption = Puroption.find(params[:id])
	end
	
	def update
		@puroption = Puroption.find(params[:id])
		if @puroption.update(puroption_params)
			flash[:success] = "The Purchase Option has been updated succesfully"
			redirect_to puroptions_path
		else
			render 'edit'
		end
	end

	def create
		@puroption = Puroption.new(puroption_params)

		if @puroption.save
			flash[:success] = "Purchase Option created succesfully."
			redirect_to puroptions_path
		else
			render 'new'
		end

	end

	private
	def puroption_params
		params.require(:puroption).permit(:puroption_name, :description)
	end

end

app/views/puroptions/_form.html.erb
<%= render 'shared/errors', obj: @puroption %>
<div class="row">
	<div class="well col-xs- col-lg-8 col-lg-offset-2 col-xs-offset-2 center">
		<%= form_for @puroption do |f| %>
		<h5 class="bold left line_Up">Purchase Option:</h5>
		<%= f.text_field :puroption_name %>
		<h5 class="bold left line_Up">Description:</h5>
		<%= f.text_area :description %>
	
		<%= f.submit(@puroption.new_record? ? "Create Purchase Option" : "Edit Purchase Option", class: "btn btn-success") %>
		<% end %>
	</div>
</div>

app/views/puroptions/edit.html.erb
<%= render 'shared/page_title', title: "Edit Purchase Options" %>
<%= render 'form' %>

app/views/puroptions/index.html.erb
<%= render 'shared/page_title', title: "All Purchase Options" %>
<p><%= link_to new_puroption_path do %>
    <i class="btn btn-lg btn-success floatright" >Add Purchase Options</i>
    <% end %>
</p>

<div class="table-container col-lg-6 col-lg-offset-3 col-xs-12">
	<table class="data-table">
		<thead>
			<tr>
				<th>Purchase Option</th>
				<th>Description</th>
				<th>Edit</th>
			</tr>
		</thead>
		<% @puroptions.each do |puroption| %>

		<tbody>
			<tr>
				<td><%= puroption.puroption_name %></td>
				<td><%= puroption.description %></td>
                <td><%= link_to puroption_path(puroption) do %>
                        <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
                    <% end %>     
                    <%= link_to edit_puroption_path(puroption) do %>
                        <i class="glyphicon glyphicon-cog" style="color:grey"></i> </td>
                    <% end %></td>
			</tr>		
		</tbody>
		<% end %>
	</table>
	    

      
      <div class="row">
                <div class= "center">
                <%= will_paginate %>
                </div>
       </div>
</div>

app/views/puroptions/new.html.erb
<%= render 'shared/page_title', title: "Create Purchase Options" %>
<%= render 'form' %>

app/views/puroptions/show.html.erb
<h1 class="title_size"> Purchase Option: <%= @puroption.puroption_name  %></h1>
<hr>
<h5 class="center">Purchase Option Description: <%= @puroption.description  %> </h5>       
<h5 class="center">Purchase Option Created <%= time_ago_in_words(@puroption.created_at) %> ago</h5>
<h5 class="center">Purchase Option Last Updated <%= time_ago_in_words(@puroption.updated_at) %> ago</h5>      



<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
				<th>Date</th>
				<th>Subject</th>
				<th>Vendor</th>
				<th>Department</th>
				<th>Purchaser</th>
				<th>Purchase Option</th>
				<th>Tax Paid</th>
				<th>Total Amount</th>
				<th>Options</th>
			</tr>
		</thead>
		
        <% @receipts.each do |receipt| %>
        <tbody>
			<tr>
				<td><%= receipt.date.try(:strftime, "%m/%d/%Y") %></td>
				<td><%= receipt.subject.subject_name %></td>
				<td><%= receipt.vendor.vendor_name %></td>
				<td><%= receipt.department.department_name %></td>
				<td><%= receipt.purchaser.purchaser_name %></td>
			    	<td><%= receipt.puroption.puroption_name %></td>
				<td>$<%= receipt.tax_amount %></td>
				<td>$<%= receipt.purchase_amount %></td>
				
                <td><%= link_to receipt_path(receipt) do %>
                        <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
                    <% end %>            
              		  <%= link_to edit_receipt_path(receipt) do %>
                        <i class="glyphicon glyphicon-cog" style="color:grey"></i>
                    <% end %></td> </td>
			</tr>		
		</tbody>
        <% end %>
        <tr> 
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td bgcolor="#FFFF00">Total</td>
        <td bgcolor="#FFFF00"> $<%= @puroption.receipts.sum(:tax_amount) %> </td>
        <td bgcolor="#FFFF00"> $<%= @puroption.receipts.sum(:purchase_amount) %> </td>
        <td></td>
        </tr>
        
        </table>

</div>