config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'logins#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :users
  get '/password', to: 'users#password'
    
  get '/register', to: 'users#new'
  
  resources :reports
  resources :receipts
  resources :subjects
  resources :purchasers
  resources :puroptions
  resources :uploads
  resources :vendors
  resources :departments
  resources :images 
  resources :receipts do
    resources :images
  end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	#belongs_to :receipts
	has_many :receipts
	validates :vendor_name, presence: true, length: { minimum: 2, maximum: 30 }
	validates :description, presence: true, length: { minimum: 2, maximum: 200 }


	
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController 
	before_action :require_user
	before_action :require_active_user
	before_action :require_admin_user, only: [:index, :edit, :update, :show]

	def index
		@vendors = Vendor.paginate(page: params[:page], per_page: 10)
	end
	
	def show
		@vendor = Vendor.find(params[:id])
		@receipts = @vendor.receipts

	end

	def new
		@vendor = Vendor.new
	end
	def edit
		@vendor = Vendor.find(params[:id])
	end
	
	def update
		@vendor = Vendor.find(params[:id])
		if @vendor.update(vendor_params)
			flash[:success] = "The Vendor has been updated succesfully"
			redirect_to vendors_path
		else
			render 'edit'
		end
	end

	def create
		@vendor = Vendor.new(vendor_params)

		if @vendor.save
			flash[:success] = "Vendor created succesfully."
			redirect_to vendors_path
		else
			render 'new'
		end

	end

	private
	def vendor_params
		params.require(:vendor).permit(:vendor_name, :description)
	end

end

app/views/vendors/_form.html.erb
<%= render 'shared/errors', obj: @vendor %>
<div class="row">
	<div class="well col-xs- col-lg-8 col-lg-offset-2 col-xs-offset-2 center">
		<%= form_for @vendor do |f| %>
		<h5 class="bold left line_Up">Subject:</h5>
		<%= f.text_field :vendor_name %>
		<h5 class="bold left line_Up">Description:</h5>
		<%= f.text_area :description %>
	
		<%= f.submit(@vendor.new_record? ? "Create Vendor" : "Edit Vendor", class: "btn btn-success") %>
		<% end %>
	</div>
</div>

app/views/vendors/edit.html.erb
<%= render 'shared/page_title', title: "Edit Vendor" %>
<%= render 'form' %>

app/views/vendors/index.html.erb
<%= render 'shared/page_title', title: "All Vendors" %>
<p><%= link_to new_vendor_path do %>
    <i class="btn btn-lg btn-success floatright" >Add Vendor</i>
    <% end %>
</p>

<div class="table-container col-lg-6 col-lg-offset-3 col-xs-12">
	<table class="data-table">
		<thead>
			<tr>
				<th>Vendor</th>
				<th>Description</th>
				<th>Edit</th>
			</tr>
		</thead>
		<% @vendors.each do |vendor| %>

		<tbody>
			<tr>
				<td><%= vendor.vendor_name %></td>
				<td><%= vendor.description %></td>
                <td><%= link_to vendor_path(vendor) do %>
                        <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
                    <% end %>     
                    <%= link_to edit_vendor_path(vendor) do %>
                        <i class="glyphicon glyphicon-cog" style="color:grey"></i> </td>
                    <% end %></td>
			</tr>		
		</tbody>
		<% end %>
	</table>
	    

      
      <div class="row">
                <div class= "center">
                <%= will_paginate %>
                </div>
       </div>
</div>

app/views/vendors/new.html.erb
<%= render 'shared/page_title', title: "Create Vendor" %>
<%= render 'form' %>

app/views/vendors/show.html.erb
<h1 class="title_size"> Vendor: <%= @vendor.vendor_name  %></h1>
<hr>
<h5 class="center">Vendor Description: <%= @vendor.description  %> </h5>       
<h5 class="center">Vendor Created <%= time_ago_in_words(@vendor.created_at) %> ago</h5>
<h5 class="center">Vendor Last Updated <%= time_ago_in_words(@vendor.updated_at) %> ago</h5>      



<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
				<th>Date</th>
				<th>Subject</th>
				<th>Vendor</th>
				<th>Department</th>
				<th>Purchaser</th>
				<th>Purchase Option</th>
				<th>Tax Paid</th>
				<th>Total Amount</th>
				<th>Options</th>
			</tr>
		</thead>
		
        <% @receipts.each do |receipt| %>
        <tbody>
			<tr>
				<td><%= receipt.date.try(:strftime, "%m/%d/%Y") %></td>
				<td><%= receipt.subject.subject_name %></td>
				<td><%= @vendor.vendor_name %></td>
				<td><%= receipt.department.department_name %></td>
				<td><%= receipt.purchaser.purchaser_name %></td>
			    	<td><%= receipt.puroption.puroption_name %></td>
				<td>$<%= receipt.tax_amount %></td>
				<td>$<%= receipt.purchase_amount %></td>
				
                <td><%= link_to receipt_path(receipt) do %>
                        <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
                    <% end %>            
              		  <%= link_to edit_receipt_path(receipt) do %>
                        <i class="glyphicon glyphicon-cog" style="color:grey"></i>
                    <% end %></td> </td>
			</tr>		
		</tbody>
        <% end %>
        <tr> 
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td bgcolor="#FFFF00">Total</td>
        <td bgcolor="#FFFF00"> $<%= @vendor.receipts.sum(:tax_amount) %> </td>
        <td bgcolor="#FFFF00"> $<%= @vendor.receipts.sum(:purchase_amount) %> </td>
        <td></td>
        </tr>
        
        </table>

</div>