config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'logins#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :users
  get '/password', to: 'users#password'
    
  get '/register', to: 'users#new'
  
  resources :reports
  resources :receipts
  resources :subjects
  resources :purchasers
  resources :puroptions
  resources :uploads
  resources :vendors
  resources :departments
  resources :images 
  resources :receipts do
    resources :images
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base

	has_many :receipts
	
	validates :subject_name, presence: true, length: { minimum: 2, maximum: 30 }
	validates :description, presence: true, length: { minimum: 2, maximum: 200 }

	
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController 
	before_action :require_user
	before_action :require_active_user
	before_action :require_admin_user, only: [:index, :edit, :update, :show]

	def index
		@subjects = Subject.paginate(page: params[:page], per_page: 10)
	end
	
	def show
		@subject = Subject.find(params[:id])
		@receipts = @subject.receipts
	end

	def new
		@subject = Subject.new
	end
	def edit
		@subject = Subject.find(params[:id])
	end
	
	def update
		@subject = Subject.find(params[:id])
		if @subject.update(subject_params)
			flash[:success] = "The Subject has been updated succesfully"
			redirect_to subjects_path
		else
			render 'edit'
		end
	end

	def create
		@subject = Subject.new(subject_params)

		if @subject.save
			flash[:success] = "Subject created succesfully."
			redirect_to subjects_path
		else
			render 'new'
		end

	end

	private
	def subject_params
		params.require(:subject).permit(:subject_name, :description)
	end

end

app/views/subjects/_form.html.erb
<%= render 'shared/errors', obj: @subject %>
<div class="row">
	<div class="well col-xs- col-lg-8 col-lg-offset-2 col-xs-offset-2 center">
		<%= form_for @subject do |f| %>
		<h5 class="bold left line_Up">Subject:</h5>
		<%= f.text_field :subject_name %>
		<h5 class="bold left line_Up">Description:</h5>
		<%= f.text_area :description %>
	
		<%= f.submit(@subject.new_record? ? "Create Subject" : "Edit Subject", class: "btn btn-success") %>
		<% end %>
	</div>
</div>

app/views/subjects/edit.html.erb
<%= render 'shared/page_title', title: "Edit Subject" %>
<%= render 'form' %>

app/views/subjects/index.html.erb
<%= render 'shared/page_title', title: "All Subjects" %>
<p><%= link_to new_subject_path do %>
    <i class="btn btn-lg btn-success floatright" >Add Subject</i>
    <% end %>
</p>

<div class="table-container col-lg-6 col-lg-offset-3 col-xs-12">
	<table class="data-table">
		<thead>
			<tr>
				<th>Subject</th>
				<th>Description</th>
				<th>Edit</th>
			</tr>
		</thead>
		<% @subjects.each do |subject| %>

		<tbody>
			<tr>
				<td><%= subject.subject_name %></td>
				<td><%= subject.description %></td>
                <td><%= link_to subject_path(subject) do %>
                        <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
                    <% end %>     
                    <%= link_to edit_subject_path(subject) do %>
                        <i class="glyphicon glyphicon-cog" style="color:grey"></i> </td>
                    <% end %></td>
			</tr>		
		</tbody>
		<% end %>
	</table>
	    

      
      <div class="row">
                <div class= "center">
                <%= will_paginate %>
                </div>
       </div>
</div>

app/views/subjects/new.html.erb
<%= render 'shared/page_title', title: "Create Subject" %>
<%= render 'form' %>

app/views/subjects/show.html.erb
<h1 class="title_size"> Subject Category: <%= @subject.subject_name  %></h1>
<hr>
<h5 class="center">Subject Description: <%= @subject.description  %> </h5>       
<h5 class="center">Subject Created <%= time_ago_in_words(@subject.created_at) %> ago</h5>
<h5 class="center">Subject Last Updated <%= time_ago_in_words(@subject.updated_at) %> ago</h5>      



<div class="table-container">
	<table class="data-table">
		<thead>
			<tr>
				<th>Date</th>
				<th>Subject</th>
				<th>Vendor</th>
				<th>Department</th>
				<th>Purchaser</th>
				<th>Purchase Option</th>
				<th>Tax Paid</th>
				<th>Total Amount</th>
				<th>Options</th>
			</tr>
		</thead>
		
        <% @receipts.each do |receipt| %>
        <tbody>
			<tr>
				<td><%= receipt.date.try(:strftime, "%m/%d/%Y") %></td>
				<td><%= receipt.subject.subject_name %></td>
				<td><%= receipt.vendor.vendor_name %></td>
				<td><%= receipt.department.department_name %></td>
				<td><%= receipt.purchaser.purchaser_name %></td>
			    <td><%= receipt.puroption.puroption_name %></td>
				<td>$<%= receipt.tax_amount %></td>
				<td>$<%= receipt.purchase_amount %></td>
				
                <td><%= link_to receipt_path(receipt) do %>
                        <i class="glyphicon glyphicon-info-sign" style="color:#377bb5"></i>
                    <% end %>            
              		  <%= link_to edit_receipt_path(receipt) do %>
                        <i class="glyphicon glyphicon-cog" style="color:grey"></i>
                    <% end %></td> </td>
			</tr>		
		</tbody>
        <% end %>
        <tr> 
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td bgcolor="#FFFF00">Total</td>
        <td bgcolor="#FFFF00"> $<%= @subject.receipts.sum(:tax_amount) %> </td>
        <td bgcolor="#FFFF00"> $<%= @subject.receipts.sum(:purchase_amount) %> </td>
        <td></td>
        </tr>
        
        </table>

</div>